#!/bin/bash

# will update moving $SNAP_USER_DATA
ECLIPSE_INI=$SNAP_USER_DATA/eclipse.ini

if [ -f "$ECLIPSE_INI"]; then
    echo "found $ECLIPSE_INI"
else
    cp $SNAP/eclipse.ini $ECLIPSE_INI
    mkdir -p $SNAP_USER_DATA/eclipse_home
    echo -Declipse.home.location=file:$SNAP_USER_DATA/eclipse_home | tee -a $ECLIPSE_INI
    mkdir -p $SNAP_USER_DATA/p2_data
    echo -Declipse.p2.data.area=$SNAP_USER_DATA/p2_data | tee -a $ECLIPSE_INI
fi

EXTRA_ARGS+=("--launcher.ini" "$ECLIPSE_INI")

# see snap plug personal-workspace
ECLIPSE_WORKSPACE=/home/$USER/eclipse-workspace
echo Using workspace at $ECLIPSE_WORKSPACE.

exec "$SNAP/eclipse" -configuration "${SNAP_USER_DATA}/${SNAP_ARCH}/configuration" -data "$ECLIPSE_WORKSPACE" "${EXTRA_ARGS[@]}" "$@"
